### ISSUE TITLE
incompatible aiohttp version

### ISSUE THREAD

**Issue by J4RF** [praw-dev/asyncprawcore#49]
**Describe the bug**
It is possible to have an incompatible version of aiohttp get installed when running `pip install asyncpraw` now that there is a new breaking (4.x) release of aiohttp. A new build running on my Jenkins server installed `aiohttp==4.0.0a1`, which caused tests to fail on instantiating `asyncpraw.Reddit()`.

**To Reproduce**
1. Run new Jenkins build for a project that depends on asyncpraw (`asyncpraw==7.5.0` in `setup.py`)
2. Build script sets up environment
3. `aiohttp==4.0.0a1` gets installed
4. Tests fail (see output below)

**Expected behavior**
asyncpraw should be installed with a compatible aiohttp version. I have resolved this for myself by adding `aiohttp==3.8.1` to my project requirements.

**Code/Logs** 
(system paths omitted)
```
Exception ignored in: <function ClientSession.__del__ at 0x7ff860902c80>
Traceback (most recent call last):
  File ".../venv/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client.py", line 269, in __del__
    if not self.closed:
  File ".../venv/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client.py", line 894, in closed
    return self._connector is None or self._connector.closed
AttributeError: _connector
Traceback (most recent call last):
  File ".../__init__.py", line 69, in run
    await self._authenticate_with_reddit(config)
  File ".../__init__.py", line 95, in _authenticate_with_reddit
    user_agent=user_agent
  File ".../venv/lib/python3.7/site-packages/asyncpraw-7.5.0-py3.7.egg/asyncpraw/reddit.py", line 314, in __init__
    self.requestor = self._prepare_asyncprawcore(requestor_class, requestor_kwargs)
  File ".../venv/lib/python3.7/site-packages/asyncpraw-7.5.0-py3.7.egg/asyncpraw/reddit.py", line 572, in _prepare_asyncprawcore
    **requestor_kwargs,
  File ".../venv/lib/python3.7/site-packages/asyncprawcore-2.3.0-py3.7.egg/asyncprawcore/requestor.py", line 47, in __init__
    loop=self.loop, timeout=aiohttp.ClientTimeout(total=None)
TypeError: __init__() got an unexpected keyword argument 'loop'
```

**System Info**
 - OS: Debian GNU/Linux 10 (buster)
 - Python: 2.7
 - Async PRAW Version: 7.5.0

**Comment by LilSpazJoekp** [comment]
When running `pip install asyncpraw`, the latest version of aiohttp (3.8.1) is installed by default. This issue only occurs when you have the pre-release version installed prior to the installation of asyncpraw or installing it with `aiohttp==4.0.0a1` afterwards.

That being said, I will pin asyncprawcore to 3.8.1 of aiohttp.

**Comment by J4RF** [comment]
This was in a brand new venv with no packages installed prior...

**Comment by LilSpazJoekp** [comment]
Would you mind running the following and paste the output of each command here please?

```bash
mkdir asyncpraw_test && cd asyncpraw_test
deactivate
python3 -m venv .venv
source .venv/bin/activate
python -V
pip -V
pip install asyncpraw
pip show aiohttp```

**Comment by J4RF** [comment]
Here you are:
```
root@jenkins ~# mkdir asyncpraw_test && cd asyncpraw_test
root@jenkins ~/asyncpraw_test# deactivate
-bash: deactivate: command not found
root@jenkins ~/asyncpraw_test# python3 -m venv .venv
root@jenkins ~/asyncpraw_test# source .venv/bin/activate
(.venv) root@jenkins ~/asyncpraw_test# python -V
Python 3.7.3
(.venv) root@jenkins ~/asyncpraw_test# pip -V
pip 18.1 from /root/asyncpraw_test/.venv/lib/python3.7/site-packages/pip (python 3.7)
(.venv) root@jenkins ~/asyncpraw_test# pip install asyncpraw --no-cache-dir
Collecting asyncpraw
  Downloading https://files.pythonhosted.org/packages/38/d1/a304e6af7bd697e2c472404974b1db882a58bf5a08e01114bbc5cc6c8f50/asyncpraw-7.5.0-py3-none-any.whl (183kB)
    100% |████████████████████████████████| 184kB 4.0MB/s
Collecting aiofiles<=0.6.0 (from asyncpraw)
  Downloading https://files.pythonhosted.org/packages/ba/21/df5eae4b6db2eb00d58428dd7f793ecbf99942fcafcea141cbf108fa72f4/aiofiles-0.6.0-py3-none-any.whl
Collecting asyncprawcore<3,>=2.1 (from asyncpraw)
  Downloading https://files.pythonhosted.org/packages/b5/53/5027b93c518933ad6c5e1ad0778de7fb844ab4a0bef545d36347448dcd3a/asyncprawcore-2.3.0-py3-none-any.whl
Collecting aiosqlite<=0.17.0 (from asyncpraw)
  Downloading https://files.pythonhosted.org/packages/a0/48/77c0092f716c4bf9460dca44f5120f70b8f71f14a12f40d22551a7152719/aiosqlite-0.17.0-py3-none-any.whl
Collecting asyncio-extras<=1.3.2 (from asyncpraw)
  Downloading https://files.pythonhosted.org/packages/ce/a1/9d4da4f02eff6ddfec720b0c67304eed0a92c8a4751aa43a9e783ef69768/asyncio_extras-1.3.2-py3-none-any.whl
Collecting update-checker>=0.18 (from asyncpraw)
  Downloading https://files.pythonhosted.org/packages/0c/ba/8dd7fa5f0b1c6a8ac62f8f57f7e794160c1f86f31c6d0fb00f582372a3e4/update_checker-0.18.0-py3-none-any.whl
Collecting aiohttp (from asyncprawcore<3,>=2.1->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/dd/fe/80c594d62a7ff07730fd2cfc3a058498087436d8c938243e0610d1928f0e/aiohttp-3.8.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 53.1MB/s
Collecting yarl (from asyncprawcore<3,>=2.1->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/80/7f/af3ecdf87e8e41da7b133f1d61f82745f8c862bdade3b56addee3ad23956/yarl-1.7.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (271kB)
    100% |████████████████████████████████| 276kB 35.0MB/s
Collecting typing_extensions>=3.7.2 (from aiosqlite<=0.17.0->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/17/61/32c3ab8951142e061587d957226b5683d1387fb22d95b4f69186d92616d1/typing_extensions-4.0.0-py3-none-any.whl
Collecting async-generator>=1.3 (from asyncio-extras<=1.3.2->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/71/52/39d20e03abd0ac9159c162ec24b93fbcaa111e8400308f2465432495ca2b/async_generator-1.10-py3-none-any.whl
Collecting requests>=2.3.0 (from update-checker>=0.18->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/92/96/144f70b972a9c0eabbd4391ef93ccd49d0f2747f4f6a2a2738e99e5adc65/requests-2.26.0-py2.py3-none-any.whl (62kB)
    100% |████████████████████████████████| 71kB 50.6MB/s
Collecting multidict<7.0,>=4.5 (from aiohttp->asyncprawcore<3,>=2.1->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/59/72/fb72624cd55492543f88ae492e5bc4dac7d6d55fde1bd4a03662b82dadf4/multidict-5.2.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (160kB)
    100% |████████████████████████████████| 163kB 54.0MB/s
Collecting attrs>=17.3.0 (from aiohttp->asyncprawcore<3,>=2.1->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/20/a9/ba6f1cd1a1517ff022b35acd6a7e4246371dfab08b8e42b829b6d07913cc/attrs-21.2.0-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 47.4MB/s
Collecting charset-normalizer<3.0,>=2.0 (from aiohttp->asyncprawcore<3,>=2.1->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/c8/27/141554fc0f42c05dd318fbb0be0e3e018da686544a3ff452762e49ccac58/charset_normalizer-2.0.8-py3-none-any.whl
Collecting asynctest==0.13.0; python_version < "3.8" (from aiohttp->asyncprawcore<3,>=2.1->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/e8/b6/8d17e169d577ca7678b11cd0d3ceebb0a6089a7f4a2de4b945fe4b1c86db/asynctest-0.13.0-py3-none-any.whl
Collecting aiosignal>=1.1.2 (from aiohttp->asyncprawcore<3,>=2.1->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/3b/87/fe94898f2d44a93a35d5aa74671ed28094d80753a1113d68b799fab6dc22/aiosignal-1.2.0-py3-none-any.whl
Collecting async-timeout<5.0,>=4.0.0a3 (from aiohttp->asyncprawcore<3,>=2.1->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/41/4a/2ca8802045b6df8dd25a0f8f7c216808e9e3bff2809efe4a36cc99d35cca/async_timeout-4.0.1-py3-none-any.whl
Collecting frozenlist>=1.1.1 (from aiohttp->asyncprawcore<3,>=2.1->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/0a/a9/c17424ae021e6c53227b0b54da4506dcae81726f8cd56e6749caafe97d16/frozenlist-1.2.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (192kB)
    100% |████████████████████████████████| 194kB 59.0MB/s
Collecting idna>=2.0 (from yarl->asyncprawcore<3,>=2.1->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/04/a2/d918dcd22354d8958fe113e1a3630137e0fc8b44859ade3063982eacd2a4/idna-3.3-py3-none-any.whl (61kB)
    100% |████████████████████████████████| 61kB 44.9MB/s
Collecting certifi>=2017.4.17 (from requests>=2.3.0->update-checker>=0.18->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl (149kB)
    100% |████████████████████████████████| 153kB 50.4MB/s
Collecting urllib3<1.27,>=1.21.1 (from requests>=2.3.0->update-checker>=0.18->asyncpraw)
  Downloading https://files.pythonhosted.org/packages/af/f4/524415c0744552cce7d8bf3669af78e8a069514405ea4fcbd0cc44733744/urllib3-1.26.7-py2.py3-none-any.whl (138kB)
    100% |████████████████████████████████| 143kB 58.4MB/s
Installing collected packages: aiofiles, multidict, attrs, charset-normalizer, asynctest, typing-extensions, idna, yarl, frozenlist, aiosignal, async-timeout, aiohttp, asyncprawcore, aiosqlite, async-generator, asyncio-extras, certifi, urllib3, requests, update-checker, asyncpraw
Successfully installed aiofiles-0.6.0 aiohttp-3.8.1 aiosignal-1.2.0 aiosqlite-0.17.0 async-generator-1.10 async-timeout-4.0.1 asyncio-extras-1.3.2 asyncpraw-7.5.0 asyncprawcore-2.3.0 asynctest-0.13.0 attrs-21.2.0 certifi-2021.10.8 charset-normalizer-2.0.8 frozenlist-1.2.0 idna-3.3 multidict-5.2.0 requests-2.26.0 typing-extensions-4.0.0 update-checker-0.18.0 urllib3-1.26.7 yarl-1.7.2
(.venv) root@jenkins ~/asyncpraw_test# pip show aiohttp
Name: aiohttp
Version: 3.8.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: None
Author-email: None
License: Apache 2
Location: /root/asyncpraw_test/.venv/lib/python3.7/site-packages
Requires: multidict, aiosignal, yarl, asynctest, charset-normalizer, async-timeout, frozenlist, attrs, typing-extensions
Required-by: asyncprawcore
```

Seems to have installed the correct version this time (note that I even used --no-cache-dir to avoid pip using the cached 3.8.1 installed earlier). What I've gathered is that this doesn't happen with `pip install asyncio`, but does happen with `python3 setup.y install` when `asyncpraw==7.5.0` is in requirements. 

  Set up a new venv > ran `python3 setup.py` > `aiohttp==4.0.0a1` gets installed.

To confirm that no other packages require aiohttp:
  Set up a new venv > completely removed asyncpraw requirement from setup.py > ran `python3 setup.py` > aiohttp does not get installed.

**Comment by LilSpazJoekp** [comment]
I'm going to close this issue. If this is still happening feel free to comment/reopen and I'll take a deeper look.
